---
- name: Install pre-requisite packages
  package: 
    name: "{{ item }}"
    state: present
  loop:
    - epel-release
    - wget
    - git
    - yum-utils
    - device-mapper-persistent-data
    - lvm2
    - python3
    - python3-pip
  when: ansible_distribution == "CentOS"